### ISSUE TITLE
`rootDir` warnings in Webstorm in test files

### ISSUE THREAD

**Issue by ildar-icoosoft** [jaredpalmer/tsdx#700] opened 2020-04-27 18:45 UTC
### Current Behavior

Steps to reproduce:
1. `npx tsdx create mylib`
2. open /test/blah.test.tsx file in WebStorm
3. You will see highlighted line: "import { Default as Thing } from '../stories/Thing.stories';":
![tsdx2](https://user-images.githubusercontent.com/29747197/80408598-db35a800-88e0-11ea-9012-393056d0929d.png)

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | "^0.13.2"
| TypeScript       | "^3.8.3"
| Browser          | Latest Chrome
| npm/Yarn         | npm 6.12.0
| Node             | v12.13.0
| Operating System | Win 10

**Comment by agilgur5** [comment] 2020-04-27 19:35
Duplicate of https://github.com/jaredpalmer/tsdx/issues/638#issuecomment-605722222, which points to upstream: https://youtrack.jetbrains.com/issue/WEB-44587?p=IDEA-236281

This doesn't occur in VS Code and the error doesn't really make sense: `src` is where your source folder is, `stories` isn't source, and so it not being part of `rootDir` should be fine.
As a result, sounds like an upstream issue to me in Webstorm, not sure if there's a way to configure it so it doesn't give this erroneous warning, I don't use Webstorm.

There is a workaround that I've mentioned in the same issue that can be used, but it's somewhat complex: https://github.com/jaredpalmer/tsdx/issues/638#issuecomment-605728767

**Closed by agilgur5** 2020-04-27 19:35 UTC

**Comment by shadesOfcodes** [comment] 2022-10-06 05:44
> Duplicate of [#638 (comment)](https://github.com/jaredpalmer/tsdx/issues/638#issuecomment-605722222), which points to upstream: https://youtrack.jetbrains.com/issue/WEB-44587?p=IDEA-236281
> 
> This doesn't occur in VS Code and the error doesn't really make sense: `src` is where your source folder is, `stories` isn't source, and so it not being part of `rootDir` should be fine. As a result, sounds like an upstream issue to me in Webstorm, not sure if there's a way to configure it so it doesn't give this erroneous warning, I don't use Webstorm.
> 
> There is a workaround that I've mentioned in the same issue that can be used, but it's somewhat complex: [#638 (comment)](https://github.com/jaredpalmer/tsdx/issues/638#issuecomment-605728767)

 encountered the same error on vscode today 
![Screenshot (662)](https://user-images.githubusercontent.com/90198430/194223760-37ae59e9-5817-4a29-b42f-a86ac971d5fd.png)

**Comment by agilgur5** [comment] 2022-10-06 13:12
@shadesOfcodes this is a 2.5 year old issue, but that's not the same error. TSDX's templates' `include` [does not have `./stories`](https://github.com/jaredpalmer/tsdx/blob/2d7981b00b2bf7363a3eeff44ff5ff698ba58c8c/templates/react-with-storybook/tsconfig.json#L3) in it.
Stories are examples, and so shouldn't be compiled as part of your build. So the error you're getting is _correct_, and not a TSDX issue.

Webstorm users, as above, were getting this in test files, which are also not in the `include`, so that was an editor/IDE issue. `tsc`, VS Code, and TSDX did not error on that.
In your case, you will get errors from `tsc` etc as well, unlike Webstorm users.

**Comment by shadesOfcodes** [comment] 2022-10-09 04:20
removing stories from  `include` causes tadx build to fail

**Comment by shadesOfcodes** [comment] 2022-10-09 04:34
> removing stories from `include` causes tsdx build to fail, tsdx is only able to build only when stories is in `include`

 ignore the above statement, build error was coming from `index.d.ts` in the include, was conflicting with input file, changing it to `asset.d.ts`, fixed it, and also i removed `./stories` from includes, everything works fine now. thanks a lot.
