### ISSUE TITLE
Add --preserveModules (similar to `babel --out-dir`)

### ISSUE THREAD

**Issue by yordis** [jaredpalmer/tsdx#321] opened 2019-11-12 05:49 UTC
### Current Behavior

We need to specify an entry point.

### Desired Behavior

Specify `--outDir` over an entry point

### Suggested Solution

I am interested in having TypeScript/Babel CLI like compilations rather than outputting a single file.

### Who does this impact? Who is this for?

All users, friendly for ESM builds without having to import everything in the entry file.

### Describe alternatives you've considered

- TypeScript compiler but I don't have support for the Babel plugins 🤷‍♂ 
- Babel CLI but I don't have support for SASS loaders 🤷‍♂

**Comment by sw-yx** [comment] 2019-12-04 09:28
popular feature request. i'll leave it to jared.

**Comment by agilgur5** [comment] 2019-12-11 23:47
@yordis it sounds like what you're looking for is [Rollup's `preserveModules` option](https://rollupjs.org/guide/en/#big-list-of-options). If that's correct, you could do that by modifying `tsdx.config.js` to add `config.preserveModules = true`:

```javascript
module.exports = {
  rollup(config, options) {
    config.preserveModules = true
    return config
  }
}
```

**Comment by agilgur5** [comment] 2020-04-19 19:52
Going to close this as a duplicate of #276 since these are around the same feature and the use-case has evolved there.

Please see #276 for discussion on `preserveModules`, #535 for a WIP flag for that, and #367 for multi-entry support.

I've updated my comment above to the latest workaround from #276 as well.

**Closed by agilgur5** 2020-04-19 19:52 UTC
Labels: feature, preserveModules
