### ISSUE TITLE
Cannot resolve dependency issue

### ISSUE THREAD

**Issue by shKwonRiiid** [jaredpalmer/tsdx#296] opened 2019-11-01 11:19 UTC
### Current Behavior
In development, cannot resolve any sources like below.

I have no idea why this problem happened. I changed paths in tsconfig

but it didn't work too.

I hope you to help or give me any idea that can solve this problem 🙏 🙇 

![image](https://user-images.githubusercontent.com/35020779/68068384-93055500-fd97-11e9-8125-b5d393ceb1c7.png)

<img width="200" src="https://user-images.githubusercontent.com/35020779/68021081-d1413c80-fce3-11e9-98ea-00c129d0f673.png"/>

#### my `tsconfig.json`
<img width="200" src="https://user-images.githubusercontent.com/35020779/68021204-21200380-fce4-11e9-8029-3e346d2a9cdd.png"/>

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | ^0.11.0
| TypeScript       | ^3.6.4
| Browser          | Chrome 78
| npm/Yarn         | v1.19.1
| Node             | v10.16.3
| Operating System | macOS Mojave v10.14.6

**Comment by sw-yx** [comment] 2019-11-04 00:39
can you replicate this in a fresh tsdx app and share a reproduction example? seems like messing with the paths may have confused absolute path resolution.

**Comment by shKwonRiiid** [comment] 2019-11-04 05:00
@sw-yx  I did some tests like below.

1. create new tsdx and copy sources => ❌ 
2. no folders. I mean flattened all files in `src` => ❌ 
3. `absolute path` changed to `relative path` (same source) => ✅ 

I think `absolute path` is not working in tsdx 😭 

Can you check this?

**Comment by arvigeus** [comment] 2019-12-11 19:11
Have you tried `baseUrl: "./src"`?

**Comment by agilgur5** [comment] 2020-03-09 19:40
Duplicate of #91

**Closed by agilgur5** 2020-03-09 19:40 UTC
