### ISSUE TITLE
Can't run test from Webstorm.

### ISSUE THREAD

**Issue by Jeff-Tian** [jaredpalmer/tsdx#434] opened 2020-01-18 03:40 UTC
### Current Behavior
Test suite failed to run from webstorm.

### Expected behavior
Zero config means it should be working seamlessly.

### Suggested solution(s)
Please share a guideline on how to make it work with webstorm.

### Additional context
![image](https://user-images.githubusercontent.com/3367820/72658092-2fc6ae80-39e7-11ea-90a6-385fdef3570a.png)
![image](https://user-images.githubusercontent.com/3367820/72658098-3d7c3400-39e7-11ea-855f-925135c0e856.png)
![image](https://user-images.githubusercontent.com/3367820/72658102-4ff66d80-39e7-11ea-912a-5fd96b60fb5f.png)

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           |0.12.0
| TypeScript       |3.5.1
| Browser          |NA
| npm/Yarn         |npm v6.11.3
| Node             | v10.15.1
| Operating System |Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64

**Comment by agilgur5** [comment] 2020-03-09 18:49
I can't read parts of this, but I believe this is a duplicate of #270 / #168 . Those are related to #354

**Closed by agilgur5** 2020-03-09 18:49 UTC
