### ISSUE TITLE
Export multiple React components?

### ISSUE THREAD

**Issue by aaronbalthaser** [jaredpalmer/tsdx#748] opened 2020-06-21 01:34 UTC
### Current Behavior

It seems the end user must import all the code from the library.

### Desired Behavior

Is there a way to import react components as stand alone components without the entire project build

### Additional context

Forgive me as this is more of a question. I could not find any forums to contact anyone. I was trying to understand if this project allows for a way to allow the end user of the library to import individual components as opposed to the entire project build. For example a typical import of all project code would be:

import { Button, Heading } from 'whatever-library';

But the user can import only the Button code and obviously any dependences used by Button component using something like:

import { Button } from 'whatever-library/lib';

Thanks.

**Comment by agilgur5** [comment] 2020-06-21 05:26
Duplicate of #713

**Closed by agilgur5** 2020-06-21 05:26 UTC
Labels: duplicate
