### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Failed to load config "react-app" to extend from. Referenced from: BaseConfig

### ISSUE THREAD

**Issue by peterthim** [jaredpalmer/tsdx#427] opened 2020-01-13 13:48 UTC
### Current Behavior
after updating in our monorepo we found that tsdx failed on
tsdx lint src 

(node:82469) UnhandledPromiseRejectionWarning: Error: Failed to load config "react-app" to extend from.
Referenced from: BaseConfig
    at configMissingError (/XXXXX/node_modules/eslint/lib/cli-engine/config-array-factory.js:233:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (//XXXXX/node_modules/eslint/lib/cli-engine/config-array-factory.js:712:23)
    at ConfigArrayFactory._loadExtends (/XXXXX/node_modules/eslint/lib/cli-engine/config-array-factory.js:617:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/XXXXX/node_modules/eslint/lib/cli-engine/config-array-factory.js:547:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/XXXXX/node_modules/eslint/lib/cli-engine/config-array-factory.js:491:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at createConfigArray (/XXXXX/node_modules/eslint/lib/cli-engine/config-array-factory.js:307:25)
    at ConfigArrayFactory.create (/XXXXX/node_modules/eslint/lib/cli-engine/config-array-factory.js:362:16)
    at createBaseConfigArray (/XXXXX/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:84:48)
(node:82469) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:82469) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 0.94s.

after rolling back/forth a few times i noticed that eslint was upped in a previous commit and from that point its failing. 

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           |
| TypeScript       |
| Browser          |
| npm/Yarn         |
| Node             | 
| Operating System |

**Comment by sw-yx** [comment] 2020-01-13 14:27
duplicate of https://github.com/jaredpalmer/tsdx/issues/428

**Closed by sw-yx** 2020-01-13 14:27 UTC
