### ISSUE TITLE
update `@rollup/plugin-replace` -- `preventAssignment` warning

### ISSUE THREAD

**Issue by y-nk** [jaredpalmer/tsdx#1052] opened 2021-06-26 04:07 UTC
Error while building:

```
@rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
```

**Comment by agilgur5** [comment] 2022-04-11 16:25
Duplicate of #981

**Closed by agilgur5** 2022-04-11 16:25 UTC
Labels: solution: duplicate, scope: dependencies, solution: workaround available, problem: removed issue template
