### ISSUE TITLE
Unit tests failed if testing code contains absolute import/TS path alias

### ISSUE THREAD

**Issue by ildar-icoosoft** [jaredpalmer/tsdx#699] opened 2020-04-27 18:26 UTC
### Current Behavior

npm run test failed because of relative import paths in tested code.

Steps to reproduce the error:
1. `npx tsdx create mylib` (select "react" option)
2. create some file in /src folder. For example: `/src/config.ts` with following content:

`export const a = 1;`
3. Import constant "a" in `/src/index.tsx` file. Here is my `/src/index.tsx` file content:
```
import * as React from 'react';
import {a} from "config";

// Delete me
export const Thing = () => {
  console.log(a);
  return <div>the snozzberries taste like snozzberries</div>;
};

```
4. run `npm run test` in mylib folder
5. You will see failed test:
![tsdx](https://user-images.githubusercontent.com/29747197/80406361-6319b300-88dd-11ea-8674-46ba33841bad.png)

### Expected behavior

test shouldn't fail because of relative paths in scripts in /src folder.

### Suggested solution(s)

I know If I replace `import {a} from "config";` with `import {a} from "./config";` then this error will be fixed. But tsconfig.json allows me to use relative path. From tsconfig.json:
```
"paths": {
      "*": ["src/*", "node_modules/*"]
    },
```
And my IDE automatically adds relative paths. And relative paths works if I run `npm run build` or `npm start`. But it doesn't work in testing.

Give the opportunity to use relative paths in tests. Or take away the opportunity to use relative paths in `/src` folder

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | "^0.13.2"
| TypeScript       | "^3.8.3"
| Browser          | Last Chrome
| npm/Yarn         | npm 6.12.0
| Node             |  v12.13.0
| Operating System | Win 10

**Comment by agilgur5** [comment] 2020-04-27 19:50
Duplicate of #91 and issues labeled with [TS Paths Aliases](https://github.com/jaredpalmer/tsdx/labels/TS%20Paths%20Aliases)

Can read my summary of the situation in https://github.com/jaredpalmer/tsdx/issues/91#issuecomment-597989579, but I'll address some of the points here:

> And relative paths works if I run `npm run build` or `npm start`

It actually doesn't work, all absolute imports get treated as externals, so the build output will be very broken.

> Give the opportunity to use relative paths in tests. Or take away the opportunity to use relative paths in `/src` folder

That's the topic of #91 et al. There is a workaround listed there, but it is fairly complex because you have to configure `tsconfig.json`, `.babelrc`, and `jest.config.js` to get it to work.

Unfortunately the incorrect use of `paths` is _very_ common with TS users as I've linked to in the summary and those patterns made their way into the templates too 😕 .
I'm planning to remove them and potentially add full support for aliases at a later date. They are fundamentally broken, but they've been around for a while (I didn't write them), so doing so is potentially breaking, but we've got a few breaking changes already lined up so it'll be a bit (maybe v0.15?). 
As it's a template change, I might be able to release as patch in v0.13.x (which has been mostly about templates) though, pending if you consider the templates to be an "API" or not.

**Closed by agilgur5** 2020-04-27 19:50 UTC
