### ISSUE TITLE
Typescript Path not resolving in published npm package

### ISSUE THREAD

**Issue by msreekm** [jaredpalmer/tsdx#325] opened 2019-11-13 02:36 UTC
### Current Behavior

 Paths defined in tsconfig does not resolve in compiled npm package.

### Expected behavior

"paths": {
      "*": ["src/*", "node_modules/*"],
      "*": ["@foo/*", "src/foo/*"],
Module not found: Can't resolve '@foo/components/ActionLink' in '/Users/sreekumarmenon/projects/xxxx/src/yyy/node_modules/xzzz.ui.core/dist'

### Suggested solution(s)
Am I missing something? do I need to create a .babelrc file or add something in package.json?
I tried creating .babelrc, but that did not help
{
  "plugins": [
    [
      "module-resolver",
      {
        "root": ["./src"],
        "alias": {
          "@rs-core/*": "./src",
          "@rs-components/*": "./src/components",
          "@rs-lib/*": "./src/lib"
        },
        "extensions": [".js", ".ts", ".tsx"]
      }
    ]
  ]
}
### Your environment

Software | Version(s)
-- | --
TSDX | ^0.11.0
TypeScript | ^3.6.4
npm | 6.4.1
Node | v10.15.0
Operating System | Mac

**Comment by sw-yx** [comment] 2019-12-04 09:52
thanks for filling, think this is a duplicate of https://github.com/jaredpalmer/tsdx/issues/336

**Closed by sw-yx** 2019-12-04 09:52 UTC

**Comment by agilgur5** [comment] 2020-03-10 20:44
Actually more of a duplicate of #425 , which is kind of a duplicate of #175 .

But afaik, TS Path aliases are only for development usage (use by yourself when creating), not production usage (use by external consumers). Using it for both would be interesting but I'm not sure if that makes sense given that those two are independent use cases and might not reflect each other.
