### ISSUE TITLE
baseUrl: "./" confuses VSCode and Jest (and me)

### ISSUE THREAD

**Issue by mikl** [jaredpalmer/tsdx#133] opened 2019-06-07 14:08 UTC
### Current Behavior

When editing a file like `src/middleware/healthCheck.ts`, and having VS Code automatically import something from another file (`src/util/checkHttpMethod.ts`) based on autocomplete, VS Code will generate a statement like:

```javascript
import { checkHttpMethod } from 'util/checkHttpMethod'
```

However, this appears to be incorrect.

When the compiler runs (from `npm start`, ie. `tsdx watch`), it will say the following:

> `No name was provided for external module 'util/checkHttpMethod' in output.globals – guessing 'checkHttpMethod$1'`

And worse yet, when I run `npm test` with a test that tries loading `src/middleware/healthCheck.ts`, it will fail with this error message.

```
 FAIL  test/middleware/healthCheck.test.ts
  ● Test suite failed to run

    Cannot find module 'util/checkHttpMethod' from 'healthCheck.ts'

    However, Jest was able to find:
    	'../../src/middleware/healthCheck.ts'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['ts', 'tsx', 'js', 'jsx', 'json', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string
```

Everything works fine if I switch the import statement to use a relative path like this:

```javascript
import { checkHttpMethod } from '../util/checkHttpMethod'
```

### Expected behavior

I would have expected things to "just work" - ie. VS Code reads the tsconfig.json and is able to figure out the right path when importing files. 

### Suggested solution(s)

I'm not sure I understand what the `baseUrl: "./"` setting is supposed to do, so I don't have any immediate suggestions. Maybe I'm just doing it wrong?

### Additional context

The test in question lives in `test/middleware/healthCheck.test.ts` and has this import statement:

```javascript
import { HEALTH_CHECK_PATH } from '../../src/middleware/healthCheck'
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.6.1
| TypeScript       | 3.5.1
| Browser          | N/A
| npm/Yarn         | npm 6.9.0
| Operating System | macOS 10.14.5

**Comment by sw-yx** [comment] 2019-06-07 15:47
vscode and typescript do read `baseUrl` fine, but this is actually more of a rollup issue. see https://github.com/palmerhq/tsdx/issues/91

**Comment by agilgur5** [comment] 2020-03-20 19:55
So actually this happens because of `paths` being set weirdly, not `baseUrl` (although `paths are relative to `baseUrl`), so pretty much a duplicate of #91. 

Will be looking to handle both `paths` and `baseUrl` with a Babel plugin, but will also probably remove the current `tsconfig.json` defaults that add `src/*` to `paths` because that's been very confusing to most users (and I don't think `src/*` is the path most aliases normally use either). `paths` inform VS Code's auto-complete as far as I can tell, so that creates even more confusion when it doesn't work.

**Closed by agilgur5** 2020-03-20 19:55 UTC
