### ISSUE TITLE
Add "preset": "ts-jest" to jest config

### ISSUE THREAD

**Issue by arvigeus** [jaredpalmer/tsdx#118] opened 2019-05-29 22:39 UTC
### Current Behavior

Some tools like VSCode's Jest plugin fail. Running tests normally works fine

### Expected behavior

Tests should work

### Suggested solution(s)

Add `"present": "ts-jest"` to `createJestConfig`.

**Comment by jaredpalmer** [comment] 2019-05-30 12:02
I think someone tried to solve this in #75, but this generated absolute paths to tsdx's jest plugins.

**Comment by agilgur5** [comment] 2020-03-09 23:02
Duplicate of #270

I'm not sure why this mentions the `ts-jest` preset since `tsdx test` doesn't use it (maybe it did at some point?)

**Closed by agilgur5** 2020-03-09 23:02 UTC
