### ISSUE TITLE
Use Jest 25

### ISSUE THREAD

**Issue by sportshead** [jaredpalmer/tsdx#664] opened 2020-04-06 04:15 UTC
### Current Behavior

Jest 24.9

### Desired Behavior

Jest 25

### Suggested Solution

Upgrade to Jest 25

### Who does this impact? Who is this for?

Everyone that uses Jest tests

### Describe alternatives you've considered

Chai

### Additional context

Maybe there will be breaking changes, I'm not sure so will have to check the source code

**Comment by agilgur5** [comment] 2020-04-06 17:56
Duplicate of #497, #471, etc. Per my comment in https://github.com/jaredpalmer/tsdx/pull/497#issuecomment-586662630, it is slightly breaking (hence why Jest used a major increment), so I'm holding off on upgrading it until ~v0.14

**Closed by agilgur5** 2020-04-06 17:56 UTC
