### ISSUE TITLE
`tslib` should be put in `dependencies`

### ISSUE THREAD

**Issue by zhaoyao91** [jaredpalmer/tsdx#412] opened 2020-01-04 16:32 UTC
### Current Behavior

Currently the `tslib` is put in `devDependencies`, but as `importHelpers` is `true` in `tsconfig.json`, the build result will only require `tslib`. In some build context, such as in electron, the `tslib` will not be packaged since it is not in `dependencies`.

### Suggested solution(s)

Two options:

- importHelpers set to false
- or, add tslib as dependencies instead of dev dependencies

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.12.0

**Comment by jaredpalmer** [comment] 2020-01-04 22:34
Correct

**Comment by agilgur5** [comment] 2020-03-19 18:12
This was a regression caused by #130 and fixed in #415, related to #413 

TSDX transpiles TS -> ESNext, then ESNext -> `preset-env`, so Babel's helper functions get generated instead of TS ones.

There's still some debate about whether those should import from `@babel/runtime` (instead of being duplicated between libraries) by default or not, but currently they don't.

**Closed by agilgur5** 2020-03-19 18:12 UTC
Labels: regression
