### ISSUE TITLE
"Cannot find name 'WindowPostMessageOptions'" -- upgrade TS version

### ISSUE THREAD

**Issue by FDiskas** [jaredpalmer/tsdx#1094] opened 2021-10-23 17:56 UTC
### Current Behavior

![image](https://user-images.githubusercontent.com/468006/138566708-14622d27-d7ad-44d3-a07d-c07f3b8eddba.png)

### Expected behavior

If I remove `DOM` from lib, I get the same error as it is shown in error when building. 

### Suggested solution(s)

Respect project `tsconfig.json` file. I know some values needs to be overwritten e.x. `target` but other values should be taken from tsconfig.

### Additional context

**tsconfig.json**
```json
{
  "compilerOptions": {
    "module": "esnext",
    "lib": ["dom", "esnext"],
    "importHelpers": true,
    "declaration": true,
    "sourceMap": true,
    "rootDir": "./src",
    "strict": false,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "skipLibCheck": true,
     "forceConsistentCasingInFileNames": true,
    "noEmit": true
  },
  "include": ["src", "types"],
  "exclude": ["node_modules", "dist"]
}
```

### Your environment

```text
  System:
    OS: Linux 5.11 Freedesktop.org 21.08.4 (Flatpak runtime) 21.08.4 (Flatpak runtime)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 11.53 GB / 31.13 GB
    Container: Yes
    Shell: 5.1.8 - /bin/sh
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v14.17.6/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
  npmPackages:
    tsdx: ^0.14.1 => 0.14.1 
    typescript: ^4.4.4 => 4.4.4 
```

**Comment by agilgur5** [comment] 2022-04-11 21:43
> Respect project `tsconfig.json` file. I know some values needs to be overwritten e.x. `target` but other values should be taken from tsconfig.

It does respect `tsconfig.json` -- that's why it's included in the templates -- and in fact [_only_ overrides `target`](https://github.com/jaredpalmer/tsdx/blob/64c50943905c983c98613944d50c20565efe6691/src/createRollupConfig.ts#L174)

The problem is not that it's not respecting `DOM` from `lib`, it's that `DOM` is outdated. TSDX is [still on TS v3](https://github.com/jaredpalmer/tsdx/blob/64c50943905c983c98613944d50c20565efe6691/package.json#L99) (and has not been maintained in some time), and [v3 DOM does not have `WindowPostMessageOptions`](https://github.com/microsoft/TypeScript/blob/b7de5e3c4cd11f9bdbcb5e741125f79ec9853bfe/src/lib/dom.generated.d.ts).

As such this is a duplicate of #926 . See that issue for workarounds such as Yarn `resolutions`

**Closed by agilgur5** 2022-04-11 21:43 UTC
Labels: solution: duplicate, scope: dependencies
