### ISSUE TITLE
Next release with rollup plugin async support

### ISSUE THREAD

**Issue by jmarceli** [jaredpalmer/tsdx#532] opened 2020-03-03 15:01 UTC
### Current Behavior

Currently, (tsdx 0.12.3) it is not possible to use rollup plugins with async functions e.g. @svgr/rollup

### Expected behavior

It should be possible

### Suggested solution(s)

It is probably already fixed on the master branch thanks to rollup-plugin-typescript2 update to [0.26](https://github.com/ezolenko/rollup-plugin-typescript2/releases/tag/0.26.0) we just need next release.

Are there any plans for the release anytime soon?

**Comment by agilgur5** [comment] 2020-03-03 19:09
Related to #512 

Yep I fixed the root cause of #294 with #506 , https://github.com/ezolenko/rollup-plugin-typescript2/pull/203, and https://github.com/puleos/object-hash/pull/90

Unfortunately, while I worked quite hard on getting the whole chain of dependencies fixed, I have 0 permissions to do anything like issue triage, merge PRs, or make releases, so it's still not released in TSDX....
Jared hasn't been doing it himself and hasn't added more maintainers so I'm strongly considering forking at this point

**Comment by jmarceli** [comment] 2020-03-03 19:42
Hi, thanks for letting me know. Maybe @jaredpalmer could add you or anyone else interested in collaboration as a maintainer. Without your update, it is not possible to use some (probably multiple) rollup plugins with async functions.

**Comment by agilgur5** [comment] 2020-03-03 19:48
Unfortunately, there have been multiple repeat issues / comments on things that already have PRs out and haven't been merged or that have already been merged and haven't been released (see #512 ).

This isn't the only thing that's bottlenecked and it's not an isolated incident 😔

**Comment by jmarceli** [comment] 2020-03-04 08:14
Thanks for letting me know. I will probably try to eject from tsdx but as you have mentioned this might be a good time for forking

**Comment by agilgur5** [comment] 2020-03-09 18:19
I emailed Jared and have been added as a collaborator to the repo, so I'll close this out as a duplicate. I still don't have permissions to publish on NPM unfortunately though, but hopefully I'll get those soon.

**Closed by agilgur5** 2020-03-09 18:19 UTC
Labels: duplicate

**Comment by agilgur5** [comment] 2020-03-20 01:38
Was given publishing rights yesterday and just released [v0.13.0](https://github.com/jaredpalmer/tsdx/releases/tag/v0.13.0). Please refer to https://github.com/jaredpalmer/tsdx/issues/512#issuecomment-601490371 with any questions.
