### ISSUE TITLE
Default github workflow has old version of node - throws error

### ISSUE THREAD

**Issue by SuperWallaby** [jaredpalmer/tsdx#1104] opened 2021-12-18 05:57 UTC
### Current Behavior

If you do `npx tsdx create mylib` and select the `base` and push it, an error occurs in the github flow.  
The error content is that node 10.x is not compatible with the dependency `@size-limit/esbuild@7.0.4:` module.  

### Suggested solution(s)
main.yml 
```
...
    strategy:
      matrix:
        node: ['10.x', '12.x', '14.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]
...
``` 
should be 
```
...
    strategy:
      matrix:
        node: [ '12.x', '14.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]
...
```
then it works fine.

**Comment by agilgur5** [comment] 2022-04-11 20:58
Duplicate of #1089 

Thanks for providing a quick fix for readers. Other method is to pin `size-limit` to a version that supports Node 10.

**Closed by agilgur5** 2022-04-11 20:58 UTC
Labels: scope: templates
