### ISSUE TITLE
How to export custom d.ts files?

### ISSUE THREAD

**Issue by PedroLucasSilva** [jaredpalmer/tsdx#1107] opened 2021-12-29 04:12 UTC
Does anyone know how I can export the d.ts file in build with the Material UI theme adaptations so that I don't need to duplicate these statements across every consumer in my library?

![image](https://user-images.githubusercontent.com/23297731/147626791-594351ff-3110-4cb3-a136-cec30a995b51.png)

**Comment by agilgur5** [comment] 2022-04-11 15:24
Duplicate of #113 . There is currently no feature for this, but you can use `rollup-plugin-copy` or something similar to put this file into your `dist` folder.

**Closed by agilgur5** 2022-04-11 15:24 UTC
Labels: solution: duplicate, solution: workaround available, problem: removed issue template
