### ISSUE TITLE
Allow each Component to be imported from respective root folder: multi-entry support

### ISSUE THREAD

**Issue by andreawyss** [jaredpalmer/tsdx#425] opened 2020-01-10 23:12 UTC
Sorry for the question, but I could not find info in the docs on how to do this.

I have a library of React Components with a source structure similar to:
https://github.com/mui-org/material-ui/tree/master/packages/material-ui/src

Is it possible to setup TSDX to build the library so that one can import individual components from their individual root folders?
```js
   import Avatar from 'my-library/Avatar';
   import Button from 'my-library/Button';
```

Currently using TSDX we are forced to import all the components from the root index
```js
   import { Avatar, Button } from 'my-library';
```

Thank you.

**Comment by ambroseus** [comment] 2020-01-11 08:53
@andreawyss  you are not alone)
https://github.com/jaredpalmer/tsdx/issues/175#issuecomment-549107959

**Comment by ambroseus** [comment] 2020-01-11 09:06
`material-ui` has additional post-build step to create sub-modules/packages for each child folder
https://github.com/mui-org/material-ui/blob/master/scripts/copy-files.js

**Comment by ambroseus** [comment] 2020-01-11 09:18
**OFF TOPIC**
 
Why in 2020 we still use bundlers with so complex configs/plugins ?? 
modern browsers/node 12 already support native modules import
so why not to throw out webpack/parcell/rollup and start using https://www.snowpack.dev ? :)

> With Snowpack you can build modern web apps (using React, Vue, etc.) without a bundler (like Webpack, Parcel, Rollup). No more waiting for your bundler to rebuild your site every time you hit save. Instead, every change is reflected in the browser instantly.

**Comment by brainkim** [comment] 2020-01-11 09:47
@ambroseus I had some of the same thoughts today after wrestling with rollup configs and deployment for a new library I want to publish. As far as I can tell, rollup’s value propositions are threefold:

1. parse and compile esmodules to other formats for dependents
2. defensively bundle your dependencies
3. tree-shake dependencies

Doesn’t 1 become obsolete when esmodules are available everywhere? And if 1 is gone, I really can’t recommend rollup for 2 or 3 insofar as with 2, I think you should either trust your dependencies or copy-paste them into your codebase, and with 3 I have never been able to cleanly add a dependency to a rollup project without having to deal with one or several of the errors/warnings listed here: https://rollupjs.org/guide/en/#troubleshooting. Rollup is an incredibly finicky consumer of code and rarely am I able to just install a dependency and get it to just compile without tweaking rollup.config.js.

I dunno.

**Comment by ambroseus** [comment] 2020-01-11 10:13
@brainkim  maybe this would be interesting for you:
https://github.com/philipwalton/rollup-native-modules-boilerplate

**Comment by agilgur5** [comment] 2020-01-21 10:35
Related to or duplicate of #365, #367, #175 , #276 , #299, #321

**Closed** 2020-03-09 19:03 UTC
Labels: duplicate
