### ISSUE TITLE
Can't use Typescript 4 features / Use project's Typescript version

### ISSUE THREAD

**Issue by thany** [jaredpalmer/tsdx#1121] opened 2022-03-11 15:49 UTC
### Current Behavior

It's compiling against its own installed version of typescript 🤨

### Expected behavior

Use the typescript version that's installed with a project, to compile it.

### Suggested solution(s)

Set typescript as a peerDependency and tell users to install it themselves. I dont know how TSDX would handle that, but dictating a specific version is ridiculous, given the amount of new features Typescript still has from version to version.

### Additional context

I don't want to be dependent on TSDX to dictate which version of Typescript can be used. Doesn't that make sense?

### Your environment

```text
  System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 10.51 GB / 31.76 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.3.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 99.0.4844.51
    Edge: Spartan (44.19041.1266.0), Chromium (99.0.1150.36)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    tsdx: 0.14.1 => 0.14.1
    typescript: 4.4.2 => 4.4.2
```

(browser is missing though, but who cares about browsers in TSDX)

**Comment by thany** [comment] 2022-03-14 10:11
A workaround, if you can even call it that, is to use `overrides` in the `package.json`:

```json
{
  "overrides": {
    "tsdx": {
      "typescript": "4.4.2"
    }
  }
}
```

Now, every single mention of the use of `overrides` entirely fails to mention that you should also **reinstall any affected packages**, so follow this change with a `npm i tsdx` should solidify this override.

However, it's a really sorry excuse for a workaround, because it reveals errors when doing a `npm list`. In my case, those errors do not appear to break anything, but still. I feel dirty 🙂  This just emphasises how important it is to keep up.

**Comment by agilgur5** [comment] 2022-04-11 16:35
Duplicate of #926 etc

Regarding peerDeps, that is _much_ easier said than done, please see https://github.com/jaredpalmer/tsdx/pull/985#issuecomment-791479189 for a summary.

**Closed by agilgur5** 2022-04-11 16:35 UTC
